version: "3.9"

services:
  api:
    build: .
    container_name: branch-api-staging
    command: gunicorn -w 2 -b 0.0.0.0:8000 wsgi:app
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db-staging:5432/postgres
      - DEBUG=False
    depends_on:
      - db-staging

  db-staging:
    image: postgres:16
    container_name: branch-db-staging
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_staging:/var/lib/postgresql/data

volumes:
  pgdata_staging:
