version: "3.9"

services:
  api:
    build: .
    container_name: branch-api-prod
    command: gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db-prod:5432/postgres
      - DEBUG=False
    depends_on:
      - db-prod

  db-prod:
    image: postgres:16
    container_name: branch-db-prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  pgdata_prod:
